name: QA Automation CI

on:
  push:
    branches: [ testNG ]
  pull_request:
    branches: [ testNG ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4



      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install dependencies
        run: mvn install -DskipTests

      - name: List Feature Files
        run: ls -R src/test/resources/features

      - name: Print Working Directory
        run: pwd

      - name: Run Tests
        run: mvn test

#      - name: Run Cucumber TestRunner
#        run: mvn -Dtest=runners.MyTestRunnerTest test
#        -Dcucumber.filter.tags="@CreateNewBrandKitWorkFlowAndVerify"